services:
  - type: web
    name: blog-app
    runtime: php
    plan: free
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    branch: main
    buildCommand: composer install
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
    disk:
      name: blog-data
      mountPath: /var/data
      sizeGB: 1
