services:
  - type: web
    name: blog-app
    env: docker
    plan: free
    repo: https://github.com/abhisheksolanki1111/blog-app
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: # will set later after deploy
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: blog_app
      - key: DB_USERNAME
        value: laravel
      - key: DB_PASSWORD
        value: secret
    disk:
      name: blog-app-disk
      mountPath: /var/www/html/storage
      sizeGB: 1
